jobs:
  - name: job-hello-world
    public: true
    plan:
      - task: print-hello-world
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: echo
            args: [hello world from inside the pipeline]
  - name: job2-hello-world
    public: true
    plan:
      - task: print-hello-world
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: echo
            args: [hello world from inside the pipeline]